INSERT INTO products (name, category, price, image_url, unit) VALUES
('Royal Feast Rice 25kg', 'Rice & Grains', 180, '', 'bag'),
('Royal Feast Rice 10kg', 'Rice & Grains', 78, '', 'bag'),
('Mama Gold Rice 5kg', 'Rice & Grains', 42, '', 'bag'),
('Indomie Noodles 40pcs', 'Rice & Grains', 95, '', 'carton'),
('Frytol Vegetable Oil 5L', 'Cooking Oil', 110, '', 'bottle'),
('Frytol Vegetable Oil 2L', 'Cooking Oil', 52, '', 'bottle'),
('Gino Vegetable Oil 3L', 'Cooking Oil', 75, '', 'bottle'),
('Palm Oil 4L', 'Cooking Oil', 65, '', 'bottle'),
('Afia Tomato Paste 70g x12', 'Tomatoes & Paste', 72, '', 'pack'),
('Tasty Tom Stew Base 400g', 'Tomatoes & Paste', 45, '', 'tin'),
('Gino Tomato Mix 400g x6', 'Tomatoes & Paste', 55, '', 'pack'),
('Fresh Tomato Paste 2kg', 'Tomatoes & Paste', 38, '', 'tin'),
('Geisha Mackerel 155g x12', 'Fish & Protein', 85, '', 'carton'),
('Lucky Star Pilchards x12', 'Fish & Protein', 90, '', 'carton'),
('Titus Sardines x12', 'Fish & Protein', 80, '', 'carton'),
('Devon King Corned Beef x6', 'Fish & Protein', 95, '', 'carton'),
('Frozen Whole Chicken 2kg', 'Chicken', 95, '', 'pack'),
('Chicken Thighs 2kg', 'Chicken', 88, '', 'pack'),
('Chicken Wings 2kg', 'Chicken', 82, '', 'pack'),
('Chicken Drumsticks 3kg', 'Chicken', 120, '', 'pack'),
('Mama''s Choice Detergent 5kg', 'Detergents', 85, '', 'bag'),
('Omo Washing Powder 2kg', 'Detergents', 48, '', 'bag'),
('Ariel Automatic 1.5kg', 'Detergents', 78, '', 'bag'),
('Sunlight Dishwash Liquid 750ml', 'Detergents', 28, '', 'bottle'),
('Dettol Antiseptic 500ml', 'Detergents', 38, '', 'bottle'),
('Morning Fresh Detergent 2L', 'Detergents', 55, '', 'bottle'),
('Milo 400g', 'Beverages', 55, '', 'tin'),
('Cowbell Milk Powder 400g', 'Beverages', 62, '', 'tin'),
('Lipton Tea Bags 100pcs', 'Beverages', 35, '', 'box'),
('Eva Table Water 1.5L x12', 'Beverages', 42, '', 'carton'),
('Maggi Seasoning Cubes x100', 'Extras', 30, '', 'pack'),
('Sugar 2kg', 'Extras', 28, '', 'bag'),
('Salt 1kg', 'Extras', 10, '', 'bag'),
('Kerosene 4L', 'Extras', 45, '', 'bottle');
