ALTER TABLE categories
    ADD COLUMN IF NOT EXISTS description TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS instructions TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS tag VARCHAR(100) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS requires_inquiry BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN IF NOT EXISTS orderable BOOLEAN NOT NULL DEFAULT true;
